title: <p align="center"> Leland Murrin </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/leland-murrin/">LinkedIn</a> |
  <a href="https://github.com/lelandjmurrin">GitHub</a>
  </p>

  <p align="justify">
  Data science graduate with an engineering background focused on financial technology, markets, business intelligence, and generative AI.
  <br><br>
  Inquisitive self-starter with a meticulous attention to data integrity and a keen curiosity for quantitative methods. 
  <br><br>
  Proficient in optimizing machine learning models, and presenting clear, insightful visualizations.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal